Patterns_KNTu_22_1_Surhai_Andrii/Pages/Brands/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Factory;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Interfaces;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Entities;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Observer;

namespace Patterns_KNTu_22_1_Surhai_Andrii.Pages.Brands
{
    public class CreateModel : PageModel
    {
        private readonly IObserver _observer;
        private readonly IDAOFactory _daoFactory;
        private readonly IBrandDAO _brandDAO;

        public Brand Brand { get; set; }
        public List<Brand> Brands { get; set; }


        public CreateModel(IDAOFactory daoFactory, IObserver observer)
        {
            this._daoFactory = daoFactory;
            this._brandDAO = _daoFactory.CreateBrandDAO();
            this._observer = observer;
            this._brandDAO.AddObserver(_observer);
        }

        public void OnGet()
        {
            Brands = _brandDAO.GetAll();
        }

        public void OnPostCreate()
        {
            string name = Convert.ToString(Request.Form["name"]);

            Brand = new Brand.Builder()
                .WithName(name)
                .Build();

            _brandDAO.Create(Brand);

            OnGet();
        }
    }
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Brands/Update.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Factory;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Interfaces;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Entities;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Observer;

namespace Patterns_KNTu_22_1_Surhai_Andrii.Pages.Brands
{
    public class UpdateModel : PageModel
    {
        private readonly IObserver _observer;
        private readonly IDAOFactory _daoFactory;
        private readonly IBrandDAO _brandDAO;

        public Brand Brand { get; set; }
        public List<Brand> Brands { get; set; }


        public UpdateModel(IDAOFactory daoFactory, IObserver observer)
        {
            this._daoFactory = daoFactory;
            this._brandDAO = _daoFactory.CreateBrandDAO();
            this._observer = observer;
            this._brandDAO.AddObserver(_observer);
        }

        public void OnGet()
        {
            Brands = _brandDAO.GetAll();
        }

        public void OnPostUpdate()
        {
            int id = Convert.ToInt32(Request.Form["brand_id"]);
            string name = Convert.ToString(Request.Form["name"]);

            Brand = new Brand.Builder()
                .WithId(id)
                .WithName(name)
                .Build();

            _brandDAO.Update(Brand);

            OnGet();
        }
    }
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Categories/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Factory;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Interfaces;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Entities;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Observer;

namespace Patterns_KNTu_22_1_Surhai_Andrii.Pages.Categories
{
    public class CreateModel : PageModel
    {
        private readonly IObserver _observer;
        private readonly IDAOFactory _daoFactory;
        private readonly ICategoryDAO _categoryDAO;

        public Category Category { get; set; }
        public List<Category> Categories { get; set; }


        public CreateModel(IDAOFactory daoFactory, IObserver observer)
        {
            this._daoFactory = daoFactory;
            this._categoryDAO = _daoFactory.CreateCategoryDAO();
            this._observer = observer;
            this._categoryDAO.AddObserver(_observer);
        }

        public void OnGet()
        {
            Categories = _categoryDAO.GetAll();
        }

        public void OnPostCreate()
        {
            string name = Convert.ToString(Request.Form["name"]);

            Category = new Category.Builder()
                .WithName(name)
                .Build();

            _categoryDAO.Create(Category);

            OnGet();
        }
    }
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Categories/Update.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Factory;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Interfaces;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Entities;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Observer;

namespace Patterns_KNTu_22_1_Surhai_Andrii.Pages.Categories
{
    public class UpdateModel : PageModel
    {
        private readonly IObserver _observer;
        private readonly IDAOFactory _daoFactory;
        private readonly ICategoryDAO _categoryDAO;

        public Category Category { get; set; }
        public List<Category> Categories { get; set; }


        public UpdateModel(IDAOFactory daoFactory, IObserver observer)
        {
            this._daoFactory = daoFactory;
            this._categoryDAO = _daoFactory.CreateCategoryDAO();
            this._observer = observer;
            this._categoryDAO.AddObserver(_observer);
        }

        public void OnGet()
        {
            Categories = _categoryDAO.GetAll();
        }

        public void OnPostUpdate()
        {
            int id = Convert.ToInt32(Request.Form["category_id"]);
            string name = Convert.ToString(Request.Form["name"]);

            Category = new Category.Builder()
                .WithId(id)
                .WithName(name)
                .Build();

            _categoryDAO.Update(Category);

            OnGet();
        }
    }
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Countries/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Factory;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Interfaces;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Entities;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Observer;

namespace Patterns_KNTu_22_1_Surhai_Andrii.Pages.Countries
{
    public class CreateModel : PageModel
    {
        private readonly IObserver _observer;
        private readonly IDAOFactory _daoFactory;
        private readonly ICountryDAO _countryDAO;

        public Country Country { get; set; }
        public List<Country> Countries { get; set; }


        public CreateModel(IDAOFactory daoFactory, IObserver observer)
        {
            this._daoFactory = daoFactory;
            this._countryDAO = _daoFactory.CreateCountryDAO();
            this._observer = observer;
            this._countryDAO.AddObserver(_observer);
        }

        public void OnGet()
        {
            Countries = _countryDAO.GetAll();
        }

        public void OnPostCreate()
        {
            string name = Convert.ToString(Request.Form["name"]);

            Country = new Country.Builder()
                .WithName(name)
                .Build();

            _countryDAO.Create(Country);

            OnGet();
        }
    }
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Countries/Update.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Factory;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Interfaces;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Entities;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Observer;

namespace Patterns_KNTu_22_1_Surhai_Andrii.Pages.Countries
{
    public class UpdateModel : PageModel
    {
        private readonly IObserver _observer;
        private readonly IDAOFactory _daoFactory;
        private readonly ICountryDAO _countryDAO;

        public Country Country { get; set; }
        public List<Country> Countries { get; set; }


        public UpdateModel(IDAOFactory daoFactory, IObserver observer)
        {
            this._daoFactory = daoFactory;
            this._countryDAO = _daoFactory.CreateCountryDAO();
            this._observer = observer;
            this._countryDAO.AddObserver(_observer);
        }

        public void OnGet()
        {
            Countries = _countryDAO.GetAll();
        }

        public void OnPostUpdate()
        {
            int id = Convert.ToInt32(Request.Form["country_id"]);
            string name = Convert.ToString(Request.Form["name"]);

            Country = new Country.Builder()
                .WithId(id)
                .WithName(name)
                .Build();

            _countryDAO.Update(Country);

            OnGet();
        }
    }
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Instrument.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Interfaces;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Entities;

namespace Patterns_KNTu_22_1_Surhai_Andrii.Pages
{
    public class InstrumentModel : PageModel
    {
        private readonly IInstrumentDAO _instrumentDAO;
        private readonly ICategoryDAO _categoryDAO;
        private readonly IBrandDAO _brandDAO;
        private readonly ICountryDAO _countryDAO;

        public Instrument Instrument { get; set; }

        public List<Instrument> Instruments { get; set; }
        public List<Category> Categories { get; set; }
        public List<Brand> Brands { get; set; }
        public List<Country> Countries { get; set; }

        
        public InstrumentModel(IInstrumentDAO instrumentDAO, ICategoryDAO categoryDAO, IBrandDAO brandDAO, ICountryDAO countryDAO)
        {
            this._instrumentDAO = instrumentDAO;
            this._categoryDAO = categoryDAO;
            this._brandDAO = brandDAO;
            this._countryDAO = countryDAO;
        }


        public void OnGet()
        {
            Instruments = _instrumentDAO.GetAll();
            Categories = _categoryDAO.GetAll();
            Brands = _brandDAO.GetAll();
            Countries = _countryDAO.GetAll();
        }


        public void OnPostCreate()
        {
            Instrument = new Instrument.Builder()
                .WithName(Convert.ToString(Request.Form["name"]))
                .WithCategoryId(Convert.ToInt32(Request.Form["category_id"]))
                .WithBrandId(Convert.ToInt32(Request.Form["brand_id"]))
                .WithCountryId(Convert.ToInt32(Request.Form["country_id"]))
                .WithYear(Convert.ToInt32(Request.Form["year"]))
                .WithPrice(Convert.ToDouble(Request.Form["price"]))
                .WithQuantity(Convert.ToInt32(Request.Form["quantity"]))
                .WithDescription(Convert.ToString(Request.Form["description"]))
                .Build();

            _instrumentDAO.Create(Instrument);

            OnGet();
        }


        public void OnPostDelete()
        {
            _instrumentDAO.Delete(Convert.ToInt32(Request.Form["instrument_id_delete"]));

            OnGet();
        }


        public void OnPostSelectById()
        {
            Instrument = _instrumentDAO.GetById(Convert.ToInt32(Request.Form["instrument_id_select"]));

            OnGet();
        }

        public JsonResult OnGetGetInstrumentById(int id)
        {
            var instrument = _instrumentDAO.GetById(id);
            return new JsonResult(instrument);
        }

        public void OnPostUpdate()
        {
            Instrument = new Instrument.Builder()
                .WithId(Convert.ToInt32(Request.Form["instrument_id_update"]))
                .WithName(Convert.ToString(Request.Form["name_update"]))
                .WithCategoryId(Convert.ToInt32(Request.Form["category_id_update"]))
                .WithBrandId(Convert.ToInt32(Request.Form["brand_id_update"]))
                .WithCountryId(Convert.ToInt32(Request.Form["country_id_update"]))
                .WithYear(Convert.ToInt32(Request.Form["year_update"]))
                .WithPrice(Convert.ToDouble(Request.Form["price_update"]))
                .WithQuantity(Convert.ToInt32(Request.Form["quantity_update"]))
                .WithDescription(Convert.ToString(Request.Form["description_update"]))
                .Build();

            _instrumentDAO.Update(Instrument);

            OnGet();
        }

    }
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Instruments/Update.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Factory;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Interfaces;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Entities;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Memento;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Observer;

namespace Patterns_KNTu_22_1_Surhai_Andrii.Pages.Instruments
{
    public class UpdateModel : PageModel
    {
        private readonly IObserver _observer;
        private readonly IDAOFactory _daoFactory;
        private readonly IInstrumentDAO _instrumentDAO;
        private readonly ICategoryDAO _categoryDAO;
        private readonly IBrandDAO _brandDAO;
        private readonly ICountryDAO _countryDAO;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public Instrument Instrument { get; set; }
        public List<Instrument> Instruments { get; set; }
        public List<Category> Categories { get; set; }
        public List<Brand> Brands { get; set; }
        public List<Country> Countries { get; set; }
        public InstrumentCaretaker InstrumentCaretaker { get; private set; }
        public UserRole UserRole { get; set; }


        public UpdateModel(IDAOFactory daoFactory, IObserver observer, InstrumentCaretaker instrumentCaretaker, IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
            string serializedUserRole = _httpContextAccessor.HttpContext.Session.GetString("UserRole");
            UserRole = JsonConvert.DeserializeObject<UserRole>(serializedUserRole);

            _daoFactory = daoFactory;
            //this._instrumentDAO = _daoFactory.CreateInstrumentDAO();
            _instrumentDAO = _daoFactory.CreateProxyInstrumentDAO(UserRole);
            _categoryDAO = _daoFactory.CreateCategoryDAO();
            _brandDAO = _daoFactory.CreateBrandDAO();
            _countryDAO = _daoFactory.CreateCountryDAO();
            _observer = observer;
            _instrumentDAO.AddObserver(_observer);
            InstrumentCaretaker = instrumentCaretaker;
            _httpContextAccessor = httpContextAccessor;
        }

        public void OnGet()
        {
            Instruments = _instrumentDAO.GetAll();
            Categories = _categoryDAO.GetAll();
            Brands = _brandDAO.GetAll();
            Countries = _countryDAO.GetAll();
        }

        public void OnPostUpdate()
        {
            int id = Convert.ToInt32(Request.Form["instrument_id"]);
            string name = Convert.ToString(Request.Form["name"]);
            int categoryId = Convert.ToInt32(Request.Form["category_id"]);
            int brandId = Convert.ToInt32(Request.Form["brand_id"]);
            int countryId = Convert.ToInt32(Request.Form["country_id"]);
            int year = Convert.ToInt32(Request.Form["year"]);
            double price = Convert.ToDouble(Request.Form["price"]);
            int quantity = Convert.ToInt32(Request.Form["quantity"]);
            string description = Convert.ToString(Request.Form["description"]);

            Instrument instrumentBeforeUpdate = _instrumentDAO.GetById(id);
            InstrumentMemento instrumentMemento = instrumentBeforeUpdate.CreateMemento();
            

            Instrument = new Instrument.Builder()
                .WithId(id)
                .WithName(name)
                .WithCategoryId(categoryId)
                .WithBrandId(brandId)
                .WithCountryId(countryId)
                .WithYear(year)
                .WithPrice(price)
                .WithQuantity(quantity)
                .WithDescription(description)
                .Build();

            try
            {
                _instrumentDAO.Update(Instrument);
                InstrumentCaretaker.AddMemento(instrumentMemento);
            }
            catch (AccessViolationException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            OnGet();
        }

        public void OnPostUndo()
        {
            if (InstrumentCaretaker.Mementos.Count > 0)
            {
                InstrumentMemento instrumentMemento = InstrumentCaretaker.GetMemento();

                if (_instrumentDAO.GetById(instrumentMemento.Id) != null)
                {
                    Instrument restoredInstrument = new Instrument.Builder().BuildEmpty();
                    restoredInstrument.RestoreMemento(instrumentMemento);
                    _instrumentDAO.Update(restoredInstrument);
                }
            }

            OnGet();
        }
    }
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Instruments/Create.cshtml
@page
@model Patterns_KNTu_22_1_Surhai_Andrii.Pages.Instruments.CreateModel
@{
}

<div>
    <h2>
        CREATE INSTRUMENT
    </h2>

    <div>
        <form method="POST" asp-page-handler="Create">
            <label for="name" class="col-form-label">Name:</label>
            <input type="text" id="name" name="name" required>
            <br>

            <label for="category_id" class="col-form-label">Category:</label>
            <select id="category_id" name="category_id" class="form-select-sm" required>
                @foreach (var category in Model.Categories)
                {
                    <option value="@category.Id">@category.Name</option>
                }
            </select>
            <br>

            <label for="brand_id" class="col-form-label">Brand:</label>
            <select id="brand_id" name="brand_id" class="form-select-sm" required>
                @foreach (var brand in Model.Brands)
                {
                    <option value="@brand.Id">@brand.Name</option>
                }
            </select>
            <br>

            <label for="country_id" class="col-form-label">Country:</label>
            <select id="country_id" name="country_id" class="form-select-sm" required>
                @foreach (var country in Model.Countries)
                {
                    <option value="@country.Id">@country.Name</option>
                }
            </select>
            <br>

            <label for="year" class="col-form-label">Year:</label>
            <select id="year" name="year" class="form-select-sm" required>
                @for (int i = DateTime.Now.Year; i >= 1901; i--)
                {
                    <option value="@i">@i</option>
                }
            </select>
            <br>

            <label for="price" class="col-form-label">Price:</label>
            <input type="number" id="price" name="price" required>
            <br>

            <label for="quantity" class="col-form-label">Quantity:</label>
            <input type="number" id="quantity" name="quantity" required>
            <br>

            <label for="description" class="col-form-label">Description:</label>
            <input type="text" id="description" name="description" required>
            <br>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    @if (Model.ModelState.ErrorCount > 0)
    {
        <div class="alert alert-danger mt-3" role="alert">
            @foreach (var modelState in Model.ModelState.Values)
            {
                foreach (var error in modelState.Errors)
                {
                    <p>@error.ErrorMessage</p>
                }
            }
        </div>
    }
</div>

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Instruments/Index.cshtml
@page
@model Patterns_KNTu_22_1_Surhai_Andrii.Pages.Instruments.IndexModel
@{
}

<div class="mb-3">
    <button type="button" name="createInstrumentButton" class="btn btn-primary" onclick="document.location.href = ('/Instruments/Create')">
        Create
    </button>
</div>

<div class="mb-3">
    <button type="button" name="updateInstrumentButton" class="btn btn-primary" onclick="document.location.href = ('/Instruments/Update')">
        Update
    </button>
</div>

<div>
    <h2>
        <p class="col-form-label">SELECT ALL</p>
    </h2>
    <table class="table" id="instrumentsTable">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Category</th>
                <th>Brand</th>
                <th>Country</th>
                <th>Year</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var instrument in Model.Instruments)
            {
                <tr>
                    <td>@instrument.Id</td>
                    <td>@instrument.Name</td>
                    <td>@Model.Categories.FirstOrDefault(c => c.Id == instrument.CategoryId)?.Name</td>
                    <td>@Model.Brands.FirstOrDefault(b => b.Id == instrument.BrandId)?.Name</td>
                    <td>@Model.Countries.FirstOrDefault(ct => ct.Id == instrument.CountryId)?.Name</td>
                    <td>@instrument.Year</td>
                    <td>@instrument.Price</td>
                    <td>@instrument.Quantity</td>
                    <td>@instrument.Description</td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div>
    <h2>
        <p class="col-form-label">DELETE</p>
    </h2>
    <form method="POST" asp-page-handler="Delete">
        <label for="instrument_id_delete" class="col-form-label">Instrument ID:</label>
        <select id="instrument_id_delete" name="instrument_id_delete" class="form-select-sm">
            @foreach (var instrument in Model.Instruments)
            {
                <option value="@instrument.Id">@instrument.Id</option>
            }
        </select>
        <br>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
@if (Model.ModelState.ErrorCount > 0)
{
    <div class="alert alert-danger mt-3" role="alert">
        @foreach (var modelState in Model.ModelState.Values)
        {
            foreach (var error in modelState.Errors)
            {
                <p>@error.ErrorMessage</p>
            }
        }
    </div>
}


<div>
    <h2>
        <p class="col-form-label">SELECT BY ID</p>
    </h2>
    <form method="POST" id="selectInstrumentForm">
        <label for="instrument_id_select" class="col-form-label">Instrument ID:</label>
        <select id="instrument_id_select" name="instrument_id_select" class="form-select-sm" required>
            @foreach (var instrument in Model.Instruments)
            {
                <option value="@instrument.Id">@instrument.Id</option>
            }
        </select>
        <br>
    </form>

    <table id="instrumentSelectTable" class="table" style="display:none;">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Category</th>
                <th>Brand</th>
                <th>Country</th>
                <th>Year</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><span id="instrumentId"></span></td>
                <td><span id="instrumentName"></span></td>
                <td><span id="instrumentCategoryId"></span></td>
                <td><span id="instrumentBrandId"></span></td>
                <td><span id="instrumentCountryId"></span></td>
                <td><span id="instrumentYear"></span></td>
                <td><span id="instrumentPrice"></span></td>
                <td><span id="instrumentQuantity"></span></td>
                <td><span id="instrumentDescription"></span></td>
            </tr>
        </tbody>
    </table>
</div>





@section scripts
{
    <script>
        $(document).ready(function () {
            $("#instrument_id_select").change(function () {
                var selectedId = $(this).val();
                if (selectedId) {
                    $.get("/Instruments/Index?handler=GetInstrumentById&id=" + selectedId, function (data) {
                        $("#instrumentId").text(data.id);
                        $("#instrumentName").text(data.name);
                        $("#instrumentCategoryId").text(data.categoryId);
                        $("#instrumentBrandId").text(data.brandId);
                        $("#instrumentCountryId").text(data.countryId);
                        $("#instrumentYear").text(data.year);
                        $("#instrumentPrice").text(data.price);
                        $("#instrumentQuantity").text(data.quantity);
                        $("#instrumentDescription").text(data.description);

                        $("#instrumentSelectTable").show();
                    });
                } else {
                    $("#instrumentSelectTable").hide();

                    $("#instrumentId, #instrumentName, #instrumentCategoryId, #instrumentBrandId, #instrumentCountryId, #instrumentYear, #instrumentPrice, #instrumentQuantity, #instrumentDescription").text('');
                }
            });
        });
    </script>
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Instruments/Update.cshtml
@page
@model Patterns_KNTu_22_1_Surhai_Andrii.Pages.Instruments.UpdateModel
@{
}


<div>
    <h2>
        UPDATE INSTRUMENT
    </h2>

    <div>
        <form method="POST" asp-page-handler="Update">
            <div>
                <label for="instrument_id" class="col-form-label">Instrument ID:</label>
                <select id="instrument_id" name="instrument_id" class="form-select-sm">
                    @foreach (var instrument in Model.Instruments)
                    {
                        <option value="@instrument.Id">@instrument.Id</option>
                    }
                </select>
            </div>
            <label for="name" class="col-form-label">Name:</label>
            <input type="text" id="name" name="name" required>
            <br>

            <label for="category_id" class="col-form-label">Category:</label>
            <select id="category_id" name="category_id" class="form-select-sm" required>
                @foreach (var category in Model.Categories)
                {
                    <option value="@category.Id">@category.Name</option>
                }
            </select>
            <br>

            <label for="brand_id" class="col-form-label">Brand:</label>
            <select id="brand_id" name="brand_id" class="form-select-sm" required>
                @foreach (var brand in Model.Brands)
                {
                    <option value="@brand.Id">@brand.Name</option>
                }
            </select>
            <br>

            <label for="country_id" class="col-form-label">Country:</label>
            <select id="country_id" name="country_id" class="form-select-sm" required>
                @foreach (var country in Model.Countries)
                {
                    <option value="@country.Id">@country.Name</option>
                }
            </select>
            <br>

            <label for="year" class="col-form-label">Year:</label>
            <select id="year" name="year" class="form-select-sm" required>
                @for (int i = DateTime.Now.Year; i >= 1901; i--)
                {
                    <option value="@i">@i</option>
                }
            </select>
            <br>

            <label for="price" class="col-form-label">Price:</label>
            <input type="number" id="price" name="price" required>
            <br>

            <label for="quantity" class="col-form-label">Quantity:</label>
            <input type="number" id="quantity" name="quantity" required>
            <br>

            <label for="description" class="col-form-label">Description:</label>
            <input type="text" id="description" name="description" required>
            <br>

            <div>
                <input type="submit" class="btn btn-primary" value="Update">
            </div>
        </form>
    </div>
    <div>
        <form method="POST" asp-page-handler="Undo">
            <div>
                <input type="submit" class="btn btn-secondary" value="Undo" @(Model.InstrumentCaretaker.Mementos.Count > 0 ? "" : "disabled")>
            </div>
        </form>
    </div>
    @if (Model.ModelState.ErrorCount > 0)
    {
        <div class="alert alert-danger mt-3" role="alert">
            @foreach (var modelState in Model.ModelState.Values)
            {
                foreach (var error in modelState.Errors)
                {
                    <p>@error.ErrorMessage</p>
                }
            }
        </div>
    }
</div>


@section scripts
{
    <script>
        $(document).ready(function () {
            $("#instrument_id").change(function () {
                var selectedId = $(this).val();
                if (selectedId) {
                    $.get("/Instruments/Index?handler=GetInstrumentById&id=" + selectedId, function (data) {
                        $("#name").val(data.name);
                        $("#category_id").val(data.categoryId);
                        $("#brand_id").val(data.brandId);
                        $("#country_id").val(data.countryId);
                        $("#year").val(data.year);
                        $("#price").val(data.price);
                        $("#quantity").val(data.quantity);
                        $("#description").val(data.description);
                    });
                } else {
                    $("#name").val('');
                    $("#category_id").val('');
                    $("#brand_id").val('');
                    $("#country_id").val('');
                    $("#year").val('');
                    $("#price").val('');
                    $("#quantity").val('');
                    $("#description").val('');
                }
            });
        });
    </script>
}