Patterns_KNTu_22_1_Surhai_Andrii/Pages/Categories/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Factory;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Interfaces;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Entities;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Observer;

namespace Patterns_KNTu_22_1_Surhai_Andrii.Pages.Categories
{
    public class CreateModel : PageModel
    {
        private readonly IObserver _observer;
        private readonly IDAOFactory _daoFactory;
        private readonly ICategoryDAO _categoryDAO;

        public Category Category { get; set; }
        public List<Category> Categories { get; set; }


        public CreateModel(IDAOFactory daoFactory, IObserver observer)
        {
            this._daoFactory = daoFactory;
            this._categoryDAO = _daoFactory.CreateCategoryDAO();
            this._observer = observer;
            this._categoryDAO.AddObserver(_observer);
        }

        public void OnGet()
        {
            Categories = _categoryDAO.GetAll();
        }

        public void OnPostCreate()
        {
            string name = Convert.ToString(Request.Form["name"]);

            Category = new Category.Builder()
                .WithName(name)
                .Build();

            _categoryDAO.Create(Category);

            OnGet();
        }
    }
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Categories/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Factory;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Interfaces;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Entities;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Observer;

namespace Patterns_KNTu_22_1_Surhai_Andrii.Pages.Categories
{
    public class IndexModel : PageModel
    {
        private readonly IObserver _observer;
        private readonly IDAOFactory _daoFactory;
        private readonly ICategoryDAO _categoryDAO;

        public Category Category { get; set; }
        public List<Category> Categories { get; set; }


        public IndexModel(IDAOFactory daoFactory, IObserver observer)
        {
            this._daoFactory = daoFactory;
            this._categoryDAO = _daoFactory.CreateCategoryDAO();
            this._observer = observer;
            this._categoryDAO.AddObserver(_observer);
        }

        public void OnGet()
        {
            Categories = _categoryDAO.GetAll();
        }

        public void OnPostDelete()
        {
            int id = Convert.ToInt32(Request.Form["category_id_delete"]);

            _categoryDAO.Delete(id);

            OnGet();
        }

        public JsonResult OnGetGetCategoryById(int id)
        {
            Category = _categoryDAO.GetById(id);
            return new JsonResult(Category);
        }
    }
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Categories/Update.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Factory;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Interfaces;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Entities;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Observer;

namespace Patterns_KNTu_22_1_Surhai_Andrii.Pages.Categories
{
    public class UpdateModel : PageModel
    {
        private readonly IObserver _observer;
        private readonly IDAOFactory _daoFactory;
        private readonly ICategoryDAO _categoryDAO;

        public Category Category { get; set; }
        public List<Category> Categories { get; set; }


        public UpdateModel(IDAOFactory daoFactory, IObserver observer)
        {
            this._daoFactory = daoFactory;
            this._categoryDAO = _daoFactory.CreateCategoryDAO();
            this._observer = observer;
            this._categoryDAO.AddObserver(_observer);
        }

        public void OnGet()
        {
            Categories = _categoryDAO.GetAll();
        }

        public void OnPostUpdate()
        {
            int id = Convert.ToInt32(Request.Form["category_id"]);
            string name = Convert.ToString(Request.Form["name"]);

            Category = new Category.Builder()
                .WithId(id)
                .WithName(name)
                .Build();

            _categoryDAO.Update(Category);

            OnGet();
        }
    }
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Category.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Interfaces;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Entities;

namespace Patterns_KNTu_22_1_Surhai_Andrii.Pages
{
    public class CategoryModel : PageModel
    {
        private readonly IBrandDAO _brandDAO;

        public Brand Brand { get; set; }

        public List<Brand> Brands { get; set; }


        public CategoryModel(IBrandDAO brandDAO)
        {
            this._brandDAO = brandDAO;
        }


        public void OnGet()
        {
            Brands = _brandDAO.GetAll();
        }


        public void OnPostCreate()
        {
            Brand = new Brand.Builder()
                .WithName(Convert.ToString(Request.Form["name"]))
                .Build();

            _brandDAO.Create(Brand);
        }


        public void OnPostDelete()
        {
            _brandDAO.Delete(Convert.ToInt32(Request.Form["category_id_delete"]));
        }


        public void OnPostSelectById()
        {
            Brand = _brandDAO.GetById(Convert.ToInt32(Request.Form["brand_id_select"]));
        }


        public void OnPostUpdate()
        {
            Brand = new Brand.Builder()
                .WithId(Convert.ToInt32(Request.Form["brand_id_update"]))
                .WithName(Convert.ToString(Request.Form["name_update"]))
                .Build();

            _brandDAO.Update(Brand);
        }

    }
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Patterns_KNTu_22_1_Surhai_Andrii.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySql.Data.MySqlClient;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Database;

namespace Patterns_KNTu_22_1_Surhai_Andrii.Pages
{
    public class IndexModel : PageModel
    {
        //public string ConnectionStatusMessage { get; private set; }

        //public Instrument instrument = new Instrument.Builder().WithName("123").WithCategoryId(1).Build();

        //public void OnGet()
        //{
        //    // This is an empty method for the initial page load.
        //}

        //public void OnPost()
        //{
        //    // Attempt to test the database connection
        //    if (TestDatabaseConnection())
        //    {
        //        ConnectionStatusMessage = "Database connection is successful.";
        //    }
        //    else
        //    {
        //        ConnectionStatusMessage = "Database connection failed.";
        //    }
        //}

        //private bool TestDatabaseConnection()
        //{
        //    using (MySqlConnection connection = DatabaseConnection.Connection)
        //    {
        //        try
        //        {
        //            return true;
        //        }
        //        catch (MySqlException ex)
        //        {
        //            return false;
        //        }
        //    }
        //}

        [BindProperty]
        public string TestResult { get; set; }

        public void OnGet()
        {
            // Initialize the page
        }

        public void OnPost()
        {
            if (Request.Form.ContainsKey("testConnectionButton"))
            {
                var connection = DatabaseConnection.Instance.GetConnection();
                try
                {
                    if (connection.State != System.Data.ConnectionState.Open)
                    {
                        connection.Open();
                    }

                    // Optionally, you can perform a test query here, like "SELECT 1", to verify the connection.
                    connection.Close();
                    TestResult = "Database connection test succeeded.";
                }
                catch (MySqlException ex)
                {
                    TestResult = $"Database connection test failed: {ex.Message}";
                }
            }
        }

    }
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Instrument.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Interfaces;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Entities;

namespace Patterns_KNTu_22_1_Surhai_Andrii.Pages
{
    public class InstrumentModel : PageModel
    {
        private readonly IInstrumentDAO _instrumentDAO;
        private readonly ICategoryDAO _categoryDAO;
        private readonly IBrandDAO _brandDAO;
        private readonly ICountryDAO _countryDAO;

        public Instrument Instrument { get; set; }

        public List<Instrument> Instruments { get; set; }
        public List<Category> Categories { get; set; }
        public List<Brand> Brands { get; set; }
        public List<Country> Countries { get; set; }

        
        public InstrumentModel(IInstrumentDAO instrumentDAO, ICategoryDAO categoryDAO, IBrandDAO brandDAO, ICountryDAO countryDAO)
        {
            this._instrumentDAO = instrumentDAO;
            this._categoryDAO = categoryDAO;
            this._brandDAO = brandDAO;
            this._countryDAO = countryDAO;
        }


        public void OnGet()
        {
            Instruments = _instrumentDAO.GetAll();
            Categories = _categoryDAO.GetAll();
            Brands = _brandDAO.GetAll();
            Countries = _countryDAO.GetAll();
        }


        public void OnPostCreate()
        {
            Instrument = new Instrument.Builder()
                .WithName(Convert.ToString(Request.Form["name"]))
                .WithCategoryId(Convert.ToInt32(Request.Form["category_id"]))
                .WithBrandId(Convert.ToInt32(Request.Form["brand_id"]))
                .WithCountryId(Convert.ToInt32(Request.Form["country_id"]))
                .WithYear(Convert.ToInt32(Request.Form["year"]))
                .WithPrice(Convert.ToDouble(Request.Form["price"]))
                .WithQuantity(Convert.ToInt32(Request.Form["quantity"]))
                .WithDescription(Convert.ToString(Request.Form["description"]))
                .Build();

            _instrumentDAO.Create(Instrument);

            OnGet();
        }


        public void OnPostDelete()
        {
            _instrumentDAO.Delete(Convert.ToInt32(Request.Form["instrument_id_delete"]));

            OnGet();
        }


        public void OnPostSelectById()
        {
            Instrument = _instrumentDAO.GetById(Convert.ToInt32(Request.Form["instrument_id_select"]));

            OnGet();
        }

        public JsonResult OnGetGetInstrumentById(int id)
        {
            var instrument = _instrumentDAO.GetById(id);
            return new JsonResult(instrument);
        }

        public void OnPostUpdate()
        {
            Instrument = new Instrument.Builder()
                .WithId(Convert.ToInt32(Request.Form["instrument_id_update"]))
                .WithName(Convert.ToString(Request.Form["name_update"]))
                .WithCategoryId(Convert.ToInt32(Request.Form["category_id_update"]))
                .WithBrandId(Convert.ToInt32(Request.Form["brand_id_update"]))
                .WithCountryId(Convert.ToInt32(Request.Form["country_id_update"]))
                .WithYear(Convert.ToInt32(Request.Form["year_update"]))
                .WithPrice(Convert.ToDouble(Request.Form["price_update"]))
                .WithQuantity(Convert.ToInt32(Request.Form["quantity_update"]))
                .WithDescription(Convert.ToString(Request.Form["description_update"]))
                .Build();

            _instrumentDAO.Update(Instrument);

            OnGet();
        }

    }
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Factory;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Interfaces;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Entities;

namespace Patterns_KNTu_22_1_Surhai_Andrii.Pages
{
    public class LoginModel : PageModel
    {
        private readonly IDAOFactory _daoFactory;
        private readonly IUserDAO _userDAO;
        private readonly IUserRoleDAO _userRoleDAO;

        public User User { get; set; }
        public UserRole UserRole { get; set; }


        public LoginModel(IDAOFactory daoFactory)
        {
            _userDAO = daoFactory.CreateUserDAO();
            _userRoleDAO = daoFactory.CreateUserRoleDAO();
        }

        public IActionResult OnPost()
        {
            string username = Request.Form["username"];
            string password = Request.Form["password"];

            User = _userDAO.GetByUsername(username);

            if (User != null && User.Password == password)
            {
                UserRole = _userRoleDAO.GetById(User.UserRoleId);

                if (UserRole != null)
                {
                    string serializedUserRole = JsonConvert.SerializeObject(UserRole);
                    HttpContext.Session.SetString("UserRole", serializedUserRole);
                    HttpContext.Session.SetString("IsAuthorized", "Yes");
                }

                return RedirectToPage("/Instruments/Index");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Incorrect Login or Password!");
                return Page();
            }
        }
    }
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySqlX.XDevAPI;

namespace Patterns_KNTu_22_1_Surhai_Andrii.Pages
{
    public class LogoutModel : PageModel
    {
        public IActionResult OnGet()
        {
            HttpContext.Session.SetString("IsAuthorized", "No");
            HttpContext.Session.SetString("UserRole", "{\"Id\":1,\"Name\":\"User\"}");

            return RedirectToPage("/Index");
        }
    }
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Registration.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Factory;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.DAO.Interfaces;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Entities;
using Patterns_KNTu_22_1_Surhai_Andrii.DAL.Observer;

namespace Patterns_KNTu_22_1_Surhai_Andrii.Pages
{
    public class RegistrationModel : PageModel
    {
        private readonly IObserver _observer;
        private readonly IDAOFactory _daoFactory;
        private readonly IUserDAO _userDAO;
        private readonly IUserRoleDAO _userRoleDAO;

        public User User { get; set; }
        public List<User> Users { get; set; }
        public List<UserRole> UsersRoles { get; set; }


        public RegistrationModel(IDAOFactory daoFactory, IObserver observer)
        {
            _daoFactory = daoFactory;
            _userDAO = _daoFactory.CreateUserDAO();
            _userRoleDAO = _daoFactory.CreateUserRoleDAO();
            _observer = observer;
            _userDAO.AddObserver(_observer);
            _userRoleDAO.AddObserver(_observer);
        }

        public void OnGet()
        {
            UsersRoles = _userRoleDAO.GetAll();
        }

        public void OnPostCreate()
        {
            int userRoleId = Convert.ToInt32(Request.Form["user_role_id"]);
            string surname = Convert.ToString(Request.Form["surname"]);
            string name = Convert.ToString(Request.Form["name"]);
            string patronymic = Convert.ToString(Request.Form["patronymic"]);
            string email = Convert.ToString(Request.Form["email"]);
            string phone = Convert.ToString(Request.Form["phone"]);
            string username = Convert.ToString(Request.Form["username"]);
            string password = Convert.ToString(Request.Form["password"]);

            User = new User.Builder()
                .WithUserRoleId(userRoleId)
                .WithSurname(surname)
                .WithName(name)
                .WithPatronymic(patronymic)
                .WithEmail(email)
                .WithPhone(phone)
                .WithUsername(username)
                .WithPassword(password)
                .Build();

            _userDAO.Create(User);

            OnGet();
        }
    }
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Category.cshtml
@page
@model Patterns_KNTu_22_1_Surhai_Andrii.Pages.CategoryModel
@{
}


<form method="POST" asp-page-handler="Create">
    <label for="name">Name:</label>
    <input type="text" id="name" name="name" required>
    <br>
    <button type="submit">Submit</button>
</form>


<form method="POST" asp-page-handler="Delete">
    <label for="category_id_delete">Id:</label>
    <input type="text" id="category_id_delete" name="category_id_delete" required>
    <br>
    <button type="submit">Submit</button>
</form>


<form method="POST" asp-page-handler="SelectById">
    <input type="text" name="brand_id_select" placeholder="Enter brand ID">
    <input type="submit" value="Submit">
</form>

@if (HttpMethods.IsPost(Request.Method)) {
    string brandId = Request.Form["brand_id_select"];
    string brandName = Model.Brand.Name;

    <div>
        <p><strong>ID:</strong> @brandId</p>
        <p><strong>Name:</strong> @brandName</p>
    </div>
}


<form method="POST" asp-page-handler="Update">
    <div>
        <label for="brand_id_update">Select a Brand:</label>
        <select id="brand_id_update" name="brand_id_update">
            @foreach (var brand in Model.Brands)
            {
                <option value="@brand.Id">@brand.Id</option>
            }
        </select>
    </div>

    <div>
        <label for="name_update">Update Brand Name:</label>
        <input type="text" id="name_update" name="name_update">
    </div>

    <div>
        <input type="submit" value="Update">
    </div>
</form>

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h2>Test Database Connection</h2>

@using Patterns_KNTu_22_1_Surhai_Andrii.DAL

<form method="post">
    <button type="submit" name="testConnectionButton">Test Database Connection</button>
</form>
<div>
    @if (!string.IsNullOrEmpty(Model.TestResult))
    {
        <p>@Model.TestResult</p>
    }
</div>

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Login.cshtml
@page
@model Patterns_KNTu_22_1_Surhai_Andrii.Pages.LoginModel
@{
    ViewData["Title"] = "Authorization";
}

<div>
    <h2>
        <p>AUTHORIZATION</p>
    </h2>
    <form method="POST">
        <label for="username" class="col-form-label">Username:</label>
        <input type="text" id="username" name="username" required>
        <br>

        <label for="password" class="col-form-label">Password:</label>
        <input type="password" id="password" name="password" required>
        <br>

        <button type="submit" class="btn btn-primary">Login</button>
    </form>
    @if (Model.ModelState.ErrorCount > 0)
    {
        <div class="alert alert-danger mt-3" role="alert">
            @foreach (var modelState in Model.ModelState.Values)
            {
                foreach (var error in modelState.Errors)
                {
                    <p>@error.ErrorMessage</p>
                }
            }
        </div>
    }
</div>

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Logout.cshtml
@page
@model Patterns_KNTu_22_1_Surhai_Andrii.Pages.LogoutModel
@{
}

Patterns_KNTu_22_1_Surhai_Andrii/Pages/Registration.cshtml
@page
@model Patterns_KNTu_22_1_Surhai_Andrii.Pages.RegistrationModel
@{
    ViewData["Title"] = "Registration";
}

<div>
    <h2>
        <p>REGISTRATION</p>
    </h2>
    <form method="POST" asp-page-handler="Create">
        <label for="surname" class="col-form-label">Surname:</label>
        <input type="text" id="surname" name="surname" required>
        <br>

        <label for="user_role_id" class="col-form-label">User Role:</label>
        <select id="user_role_id" name="user_role_id" class="form-select-sm" required>
            @foreach (var userRole in Model.UsersRoles)
            {
                <option value="@userRole.Id">@userRole.Name</option>
            }
        </select>
        <br>


        <label for="name" class="col-form-label">Name:</label>
        <input type="text" id="name" name="name" required>
        <br>

        <label for="patronymic" class="col-form-label">Patronymic:</label>
        <input type="text" id="patronymic" name="patronymic" required>
        <br>

        <label for="email" class="col-form-label">Email:</label>
        <input type="email" id="email" name="email" required>
        <br>

        <label for="phone" class="col-form-label">Phone:</label>
        <input type="text" id="phone" name="phone" required>
        <br>

        <label for="username" class="col-form-label">Username:</label>
        <input type="text" id="username" name="username" required>
        <br>

        <label for="password" class="col-form-label">Password:</label>
        <input type="password" id="password" name="password" required>
        <br>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>